name:                l-system
version:             0.1.0.0
github:              "BorisNikulin/l-system"
license:             MIT
author:              "Boris Nikulin"
maintainer:          "NikulinBE@gmail.com"
copyright:           "2018 Boris Nikulin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/BorisNikulin/l-system#readme>

dependencies:
    - base >= 4.7 && < 5
    - recursion-schemes >= 5 && < 6
    - free >= 5 && < 6

ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs

library:
  source-dirs: src

executables:
  l-system-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
        - l-system

tests:
  l-system-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
        - l-system
